<div style="background:url('/img/content_text_line.png')bottom no-repeat;">
    <h1 class="header">PHP 异常处理</h1>
</div>
<div>

<p><b>异常（Exception）用于在指定的错误发生时改变脚本的正常流程。</b></p>

<h1>什么是异常？</h1>

<p>PHP 5 提供了一种新的面向对象的错误处理方法。</p>
<p>异常处理用于在指定的错误（异常）情况发生时改变脚本的正常流程。这种情况称为异常。</p>
<p>当异常被触发时，通常会发生：</p>

<ul>
<li>当前代码状态被保存</li>
<li>代码执行被切换到预定义的异常处理器函数</li>
<li>根据情况，处理器也许会从保存的代码状态重新开始执行代码，终止脚本执行，或从代码中另外的位置继续执行脚本</li>

<p>我们将展示不同的错误处理方法：</p>

<ul>
<li>异常的基本使用</li>
<li>创建自定义的异常处理器</li>
<li>多个异常</li>
<li>重新抛出异常</li>
<li>设置顶层异常处理器</li>
</ul>

<h1>异常的基本使用</h1>

<p>当异常被抛出时，其后的代码不会继续执行，PHP 会尝试查找匹配的 "catch" 代码块。</p>
<p>如果异常没有被捕获，而且又没用使用 set_exception_handler() 作相应的处理的话，那么将发生一个严重的错误（致命错误），并且输出 "Uncaught Exception" （未捕获异常）的错误消息。 </p>
<p>让我们尝试抛出一个异常，同时不去捕获它：</p>

<code>
&lt;?php<br />
//create&nbspfunction&nbspwith&nbspan&nbspexception<br />
function&nbspcheckNum($number)<br />
&nbsp{<br />
&nbspif($number&gt;1)<br />
&nbsp&nbsp{<br />
&nbsp&nbspthrow&nbspnew&nbspException("Value&nbspmust&nbspbe&nbsp1&nbspor&nbspbelow");<br />
&nbsp&nbsp}<br />
&nbspreturn&nbsptrue;<br />
&nbsp}<br />
<br />
//trigger&nbspexception<br />
checkNum(2);<br />
?&gt;
</code>

<p>上面的代码会获得类似这样的一个错误：</p>

<code>
Fatal error: Uncaught exception 'Exception' <br />
with message 'Value must be 1 or below' in C:\webfolder\test.php:6 <br />
Stack trace: #0 C:\webfolder\test.php(12): <br />
checkNum(28) #1 {main} thrown in C:\webfolder\test.php on line 6
</code>

<h2>Try, throw 和 catch</h2>

<p>要避免上面例子出现的错误，我们需要创建适当的代码来处理异常。</p>
<p>处理处理程序应当包括：</p>
<p>1.Try - 使用异常的函数应该位于 "try" 代码块内。如果没有触发异常，则代码将照常继续执行。但是如果异常被触发，会抛出一个异常。</p>
<p>2.Throw - 这里规定如何触发异常。每一个 "throw" 必须对应至少一个 "catch"</p>
<p>3.Catch - "catch" 代码块会捕获异常，并创建一个包含异常信息的对象</p>
<p>让我们触发一个异常：</p>

<code>
&lt;?php<br />
//创建可抛出一个异常的函数<br />
function&nbspcheckNum($number)<br />
&nbsp{<br />
&nbspif($number&gt;1)<br />
&nbsp&nbsp{<br />
&nbsp&nbspthrow&nbspnew&nbspException("Value&nbspmust&nbspbe&nbsp1&nbspor&nbspbelow");<br />
&nbsp&nbsp}<br />
&nbspreturn&nbsptrue;<br />
&nbsp}<br />
<br />
//在&nbsp"try"&nbsp代码块中触发异常<br />
try<br />
&nbsp{<br />
&nbspcheckNum(2);<br />
&nbsp//If&nbspthe&nbspexception&nbspis&nbspthrown,&nbspthis&nbsptext&nbspwill&nbspnot&nbspbe&nbspshown<br />
&nbspecho&nbsp'If&nbspyou&nbspsee&nbspthis,&nbspthe&nbspnumber&nbspis&nbsp1&nbspor&nbspbelow';<br />
&nbsp}<br />
<br />
//捕获异常<br />
catch(Exception&nbsp$e)<br />
&nbsp{<br />
&nbspecho&nbsp'Message:&nbsp'&nbsp.$e-&gt;getMessage();<br />
&nbsp}<br />
?&gt;
</code>

<p>上面代码将获得类似这样一个错误：</p>

<code>Message: Value must be 1 or below </code>

<h2>例子解释：</h2>

<p>上面的代码抛出了一个异常，并捕获了它：</p>
<p>1.创建 checkNum() 函数。它检测数字是否大于 1。如果是，则抛出一个异常。</p>
<p>2.在 "try" 代码块中调用 checkNum() 函数。</p>
<p>3.checkNum() 函数中的异常被抛出</p>
<p>4."catch" 代码块接收到该异常，并创建一个包含异常信息的对象 ($e)。</p>
<p>5.通过从这个 exception 对象调用 $e->getMessage()，输出来自该异常的错误消息</p>
<p>不过，为了遵循"每个 throw 必须对应一个 catch"的原则，可以设置一个顶层的异常处理器来处理漏掉的错误。</p>

<h1>创建一个自定义的 Exception 类</h1>

<p>创建自定义的异常处理程序非常简单。我们简单地创建了一个专门的类，当 PHP 中发生异常时，可调用其函数。该类必须是 exception 类的一个扩展。</p>
<p>这个自定义的 exception 类继承了 PHP 的 exception 类的所有属性，您可向其添加自定义的函数。</p>
<p>我们开始创建 exception 类：</p>

<code>
&lt;?php<br />
class&nbspcustomException&nbspextends&nbspException<br />
&nbsp{<br />
&nbsppublic&nbspfunction&nbsperrorMessage()<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//error&nbspmessage<br />
&nbsp&nbsp$errorMsg&nbsp=&nbsp'Error&nbspon&nbspline&nbsp'.$this-&gt;getLine().'&nbspin&nbsp'.$this-&gt;getFile()<br />
&nbsp&nbsp.':&nbsp&lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt;&nbspis&nbspnot&nbspa&nbspvalid&nbspE-Mail&nbspaddress';<br />
&nbsp&nbspreturn&nbsp$errorMsg;<br />
&nbsp&nbsp}<br />
&nbsp}<br />
<br />
$email&nbsp=&nbsp"someone@example...com";<br />
<br />
try<br />
&nbsp{<br />
&nbsp//check&nbspif&nbsp<br />
&nbspif(filter_var($email,&nbspFILTER_VALIDATE_EMAIL)&nbsp===&nbspFALSE)<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//throw&nbspexception&nbspif&nbspemail&nbspis&nbspnot&nbspvalid<br />
&nbsp&nbspthrow&nbspnew&nbspcustomException($email);<br />
&nbsp&nbsp}<br />
&nbsp}<br />
<br />
catch&nbsp(customException&nbsp$e)<br />
&nbsp{<br />
&nbsp//display&nbspcustom&nbspmessage<br />
&nbspecho&nbsp$e-&gt;errorMessage();<br />
&nbsp}<br />
?&gt;
</code>

<p>这个新的类是旧的 exception 类的副本，外加 errorMessage() 函数。正因为它是旧类的副本，因此它从旧类继承了属性和方法，我们可以使用 exception 类的方法，比如 getLine() 、 getFile() 以及 getMessage()。</p>

<h2>例子解释：</h2>

<p>上面的代码抛出了一个异常，并通过一个自定义的 exception 类来捕获它：</p>
<p>1.customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</p>
<p>2.创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一条错误消息</p>
<p>3.把 $email 变量设置为不合法的 e-mail 地址字符串</p>
<p>4.执行 "try" 代码块，由于 e-mail 地址不合法，因此抛出一个异常</p>
<p>5."catch" 代码块捕获异常，并显示错误消息</p>

<h1>多个异常</h1>

<p>可以为一段脚本使用多个异常，来检测多种情况。</p>
<p>可以使用多个 if..else 代码块，或一个 switch 代码块，或者嵌套多个异常。这些异常能够使用不同的 exception 类，并返回不同的错误消息：</p>

<code>
&lt;?php<br />
class&nbspcustomException&nbspextends&nbspException<br />
{<br />
public&nbspfunction&nbsperrorMessage()<br />
{<br />
//error&nbspmessage<br />
$errorMsg&nbsp=&nbsp'Error&nbspon&nbspline&nbsp'.$this-&gt;getLine().'&nbspin&nbsp'.$this-&gt;getFile()<br />
.':&nbsp&lt;b&gt;'.$this-&gt;getMessage().'&lt;/b&gt;&nbspis&nbspnot&nbspa&nbspvalid&nbspE-Mail&nbspaddress';<br />
return&nbsp$errorMsg;<br />
}<br />
}<br />
<br />
$email&nbsp=&nbsp"someone@example.com";<br />
<br />
try<br />
&nbsp{<br />
&nbsp//check&nbspif&nbsp<br />
&nbspif(filter_var($email,&nbspFILTER_VALIDATE_EMAIL)&nbsp===&nbspFALSE)<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//throw&nbspexception&nbspif&nbspemail&nbspis&nbspnot&nbspvalid<br />
&nbsp&nbspthrow&nbspnew&nbspcustomException($email);<br />
&nbsp&nbsp}<br />
&nbsp//check&nbspfor&nbsp"example"&nbspin&nbspmail&nbspaddress<br />
&nbspif(strpos($email,&nbsp"example")&nbsp!==&nbspFALSE)<br />
&nbsp&nbsp{<br />
&nbsp&nbspthrow&nbspnew&nbspException("$email&nbspis&nbspan&nbspexample&nbspe-mail");<br />
&nbsp&nbsp}<br />
&nbsp}<br />
<br />
catch&nbsp(customException&nbsp$e)<br />
&nbsp{<br />
&nbspecho&nbsp$e-&gt;errorMessage();<br />
&nbsp}<br />
<br />
catch(Exception&nbsp$e)<br />
&nbsp{<br />
&nbspecho&nbsp$e-&gt;getMessage();<br />
&nbsp}<br />
?&gt;
</code>

<h2>例子解释：</h2>

<p>上面的代码测试了两种条件，如何任何条件不成立，则抛出一个异常：</p>
<p>1.customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</p>
<p>2.创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</p>
<p>3.执行 "try" 代码块，在第一个条件下，不会抛出异常。</p>
<p>4.由于 e-mail 含有字符串 "example"，第二个条件会触发异常。</p>
<p>5."catch" 代码块会捕获异常，并显示恰当的错误消息</p>
<p>如果没有捕获 customException，紧紧捕获了 base exception，则在那里处理异常。</p>

<h1>重新抛出异常</h1>

<p>有时，当异常被抛出时，您也许希望以不同于标准的方式对它进行处理。可以在一个 "catch" 代码块中再次抛出异常。</p>
<p>脚本应该对用户隐藏系统错误。对程序员来说，系统错误也许很重要，但是用户对它们并不感兴趣。为了让用户更容易使用，您可以再次抛出带有对用户比较友好的消息的异常：</p>

<code>
&lt;?php<br />
class&nbspcustomException&nbspextends&nbspException<br />
&nbsp{<br />
&nbsppublic&nbspfunction&nbsperrorMessage()<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//error&nbspmessage<br />
&nbsp&nbsp$errorMsg&nbsp=&nbsp$this-&gt;getMessage().'&nbspis&nbspnot&nbspa&nbspvalid&nbspE-Mail&nbspaddress.';<br />
&nbsp&nbspreturn&nbsp$errorMsg;<br />
&nbsp&nbsp}<br />
&nbsp}<br />
<br />
$email&nbsp=&nbsp"someone@example.com";<br />
<br />
try<br />
&nbsp{<br />
&nbsptry<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//check&nbspfor&nbsp"example"&nbspin&nbspmail&nbspaddress<br />
&nbsp&nbspif(strpos($email,&nbsp"example")&nbsp!==&nbspFALSE)<br />
&nbsp&nbsp&nbsp{<br />
&nbsp&nbsp&nbsp//throw&nbspexception&nbspif&nbspemail&nbspis&nbspnot&nbspvalid<br />
&nbsp&nbsp&nbspthrow&nbspnew&nbspException($email);<br />
&nbsp&nbsp&nbsp}<br />
&nbsp&nbsp}<br />
&nbspcatch(Exception&nbsp$e)<br />
&nbsp&nbsp{<br />
&nbsp&nbsp//re-throw&nbspexception<br />
&nbsp&nbspthrow&nbspnew&nbspcustomException($email);<br />
&nbsp&nbsp}<br />
&nbsp}<br />
<br />
catch&nbsp(customException&nbsp$e)<br />
&nbsp{<br />
&nbsp//display&nbspcustom&nbspmessage<br />
&nbspecho&nbsp$e-&gt;errorMessage();<br />
&nbsp}<br />
?&gt;
</code>

<h2>例子解释：</h2>

<p>上面的代码检测在邮件地址中是否含有字符串 "example"。如果有，则再次抛出异常：</p>
<p>1.customException() 类是作为旧的 exception 类的一个扩展来创建的。这样它就继承了旧类的所有属性和方法。</p>
<p>2.创建 errorMessage() 函数。如果 e-mail 地址不合法，则该函数返回一个错误消息。</p>
<p>3.把 $email 变量设置为一个有效的邮件地址，但含有字符串 "example"。</p>
<p>4."try" 代码块包含另一个 "try" 代码块，这样就可以再次抛出异常。</p>
<p>5.由于 e-mail 包含字符串 "example"，因此触发异常。</p>
<p>6."catch" 捕获到该异常，并重新抛出 "customException"。</p>
<p>7.捕获到 "customException"，并显示一条错误消息。</p>
<p>如果在其目前的 "try" 代码块中异常没有被捕获，则它将在更高层级上查找 catch 代码块。</p>

<h1>设置顶层异常处理器 （Top Level Exception Handler）</h1>

<p>set_exception_handler() 函数可设置处理所有未捕获异常的用户定义函数。</p>

<code>
&lt;?php<br />
function&nbspmyException($exception)<br />
{<br />
echo&nbsp"&lt;b&gt;Exception:&lt;/b&gt;&nbsp"&nbsp,&nbsp$exception-&gt;getMessage();<br />
}<br />
<br />
set_exception_handler('myException');<br />
<br />
throw&nbspnew&nbspException('Uncaught&nbspException&nbspoccurred');<br />
?&gt;
</code>

<p>以上代码的输出应该类似这样：</p>

<code>Exception: Uncaught Exception occurred</code>

<p>在上面的代码中，不存在 "catch" 代码块，而是触发顶层的异常处理程序。应该使用此函数来捕获所有未被捕获的异常。</p>

<h1>异常的规则</h1>

<ul>
<li>需要进行异常处理的代码应该放入 try 代码块内，以便捕获潜在的异常。</li>
<li>每个 try 或 throw 代码块必须至少拥有一个对应的 catch 代码块。</li>
<li>使用多个 catch 代码块可以捕获不同种类的异常。</li>
<li>可以在 try 代码块内的 catch 代码块中再次抛出（re-thrown）异常。</li>
</ul>
<p><b>简而言之：如果抛出了异常，就必须捕获它。</b></p>

</div>
